spring.application.name=AquariumWarehousingSupportSystem

server.port=8081
jwt.secret=key/minh;amii@2210
jwt.get.token.uri=/authenticate

#Mysql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/gmt_warehouse_sys?useSSL=false
spring.datasource.username=root
spring.datasource.password=Q@z32147985
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
spring.jpa.show-sql=true
